# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
goos:
  - linux:
   goarch:
    - arm
    - arm64
   goarm:
    - 8 
archives:
- id: deploy-archive
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  files:
   - config.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
